feat: install the dependencies

diff --git a/nexus_command/fast_download_video b/nexus_command/fast_download_video
--- a/nexus_command/fast_download_video
+++ b/nexus_command/fast_download_video
@@ -1,11 +1,41 @@
 #!/bin/bash
+#set -euo pipefail
+
+# COLORS
+G='\033[1;32m'      # GREEN
+R='\033[1;31m'      # RED
+B='\033[0;33m'      # BLUE
+P='\033[1;35m'      # PURPLE
+O='\033[1;93m'      # ORANGE
+D='\033[0m'         # DEFAULT
+
+# THE PROJECT STAR HERE
+clear
+echo ""
+echo -e "${R}██████╗░██╗░░░██╗  ██████╗░░█████╗░░█████╗░████████╗░█████╗░██████╗░  ░██████╗░█████╗░██╗░░░░░░█████╗░"
+echo -e     "██╔══██╗╚██╗░██╔╝  ██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗  ██╔════╝██╔══██╗██║░░░░░██╔══██╗"
+echo -e     "██████╦╝░╚████╔╝░  ██║░░██║██║░░██║██║░░╚═╝░░░██║░░░██║░░██║██████╔╝  ╚█████╗░██║░░██║██║░░░░░██║░░██║"
+echo -e     "██╔══██╗░░╚██╔╝░░  ██║░░██║██║░░██║██║░░██╗░░░██║░░░██║░░██║██╔══██╗  ░╚═══██╗██║░░██║██║░░░░░██║░░██║"
+echo -e     "██████╦╝░░░██║░░░  ██████╔╝╚█████╔╝╚█████╔╝░░░██║░░░╚█████╔╝██║░░██║  ██████╔╝╚█████╔╝███████╗╚█████╔╝"
+echo -e     "╚═════╝░░░░╚═╝░░░  ╚═════╝░░╚════╝░░╚════╝░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝  ╚═════╝░░╚════╝░╚══════╝░╚════╝░${D}"
+echo ""
+
 
 for cmd in yt-dlp ffmpeg aria2c; do
-    if ! command -v $cmd &> /dev/null; then
-        echo "Error: $cmd not found. Install it: sudo pacman -S yt-dlp ffmpeg aria2"
+    if !command -v $cmd &> /dev/null; then
+        echo "Error: $cmd not found. Install it:"
+        sudo pacman -S yt-dlp ffmpeg aria2
+        exit 0
+    fi
+done
+
+for cmd in yt-dlp ffmpeg aria2c; do
+    if !command -v $cmd &> /dev/null; then
+        echo "Program fail. Intall the dependencies"
         exit 1
     fi
 done
+
 
 # link here
 read -p "Put here the link: " URL
